# Record name
name: octoshop.checkout::lang.order.label

# Model Form Field configuration
form: $/octoshop/checkout/models/order/fields.yaml

# Model Class name
modelClass: Octoshop\Checkout\Models\Order

# Default redirect location
defaultRedirect: octoshop/checkout/orders

# Create page
create:
    title: backend::lang.form.create_title
    redirect: octoshop/checkout/orders/update/:id
    redirectClose: octoshop/checkout/orders

# Update page
update:
    title: backend::lang.form.update_title
    redirect: octoshop/checkout/orders
    redirectClose: octoshop/checkout/orders
